
server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry : false
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/my_database
    username : root
    password : muskan
    driverClassName : com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate :
      ddl-auto : update







